# These are supported funding model platforms

github: Etyuhibosecyu
patreon: Red_Star_Soft
Payeer: P19926501
Monero: 4AHvZX6BHNcZ6T2iCq4Ruu3nGXipEzjdyYPpvLGMqCzXartsMJoFBxRjXEeKRXDu96JCyYvvPunNnSMBeKYTS8iXBw9z6p3
