<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<DefineConstants>$(DefineConstants)</DefineConstants>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<PlatformTarget>AnyCPU</PlatformTarget>
		<Platforms>AnyCPU</Platforms>
		<AssemblyName>$(MSBuildProjectName)</AssemblyName>
		<TargetFrameworkProfile />
	</PropertyGroup>
	<ItemGroup Condition="'$(Platform)' == 'x86'">
		<Content Include="xmpir32.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	<ItemGroup Condition="'$(Platform)' != 'x86'">
		<Content Include="xmpir64.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\NStar.Dictionaries\NStar.Dictionaries.csproj" />
	  <ProjectReference Include="..\NStar.Linq\NStar.Linq.csproj" />
	</ItemGroup>
</Project>