namespace Dictionaries.NStar;

public static class RedStarLinqDictionaries
{
	public static Dictionary<TKey, TValue> ToDictionary<T, TKey, TValue>(this G.IEnumerable<T> source, Func<T, TKey> function, Func<T, TValue> function2) where TKey : notnull => new(RedStarLinq.ToList(source, function), RedStarLinq.ToList(source, function2));
	public static Dictionary<TKey, TValue> ToDictionary<T, TKey, TValue>(this G.IEnumerable<T> source, Func<T, int, TKey> function, Func<T, int, TValue> function2) where TKey : notnull => new(RedStarLinq.ToList(source, function), RedStarLinq.ToList(source, function2));
	public static Dictionary<TKey, TValue> ToDictionary<T, TKey, TValue>(this G.IEnumerable<T> source, Func<T, TKey> function, Func<T, TValue> function2, G.IEqualityComparer<TKey> comparer) where TKey : notnull => new(RedStarLinq.ToList(source, function), RedStarLinq.ToList(source, function2), comparer);
	public static Dictionary<TKey, TValue> ToDictionary<T, TKey, TValue>(this G.IEnumerable<T> source, Func<T, int, TKey> function, Func<T, int, TValue> function2, G.IEqualityComparer<TKey> comparer) where TKey : notnull => new(RedStarLinq.ToList(source, function), RedStarLinq.ToList(source, function2), comparer);
	public static Dictionary<TKey, TValue> ToDictionary<T, TKey, TValue>(this G.IEnumerable<T> source, Func<T, TKey> function, Func<T, TValue> function2, Func<TKey, TKey, bool> equalFunction) where TKey : notnull => new(RedStarLinq.ToList(source, function), RedStarLinq.ToList(source, function2), equalFunction);
	public static Dictionary<TKey, TValue> ToDictionary<T, TKey, TValue>(this G.IEnumerable<T> source, Func<T, int, TKey> function, Func<T, int, TValue> function2, Func<TKey, TKey, bool> equalFunction) where TKey : notnull => new(RedStarLinq.ToList(source, function), RedStarLinq.ToList(source, function2), equalFunction);
	public static Dictionary<TKey, TValue> ToDictionary<T, TKey, TValue>(this G.IEnumerable<T> source, Func<T, TKey> function, Func<T, TValue> function2, Func<TKey, TKey, bool> equalFunction, Func<TKey, int> hashCodeFunction) where TKey : notnull => new(RedStarLinq.ToList(source, function), RedStarLinq.ToList(source, function2), equalFunction, hashCodeFunction);
	public static Dictionary<TKey, TValue> ToDictionary<T, TKey, TValue>(this G.IEnumerable<T> source, Func<T, int, TKey> function, Func<T, int, TValue> function2, Func<TKey, TKey, bool> equalFunction, Func<TKey, int> hashCodeFunction) where TKey : notnull => new(RedStarLinq.ToList(source, function), RedStarLinq.ToList(source, function2), equalFunction, hashCodeFunction);
	public static Dictionary<TKey, TValue> ToDictionary<T, TKey, TValue>(this G.IEnumerable<T> source, Func<T, (TKey, TValue)> function) where TKey : notnull => new(RedStarLinq.ToList(source, function));
	public static Dictionary<TKey, TValue> ToDictionary<T, TKey, TValue>(this G.IEnumerable<T> source, Func<T, int, (TKey, TValue)> function) where TKey : notnull => new(RedStarLinq.ToList(source, function));
	public static Dictionary<TKey, TValue> ToDictionary<T, TKey, TValue>(this G.IEnumerable<T> source, Func<T, (TKey, TValue)> function, G.IEqualityComparer<TKey> comparer) where TKey : notnull => new(RedStarLinq.ToList(source, function), comparer);
	public static Dictionary<TKey, TValue> ToDictionary<T, TKey, TValue>(this G.IEnumerable<T> source, Func<T, int, (TKey, TValue)> function, G.IEqualityComparer<TKey> comparer) where TKey : notnull => new(RedStarLinq.ToList(source, function), comparer);
	public static Dictionary<TKey, TValue> ToDictionary<T, TKey, TValue>(this G.IEnumerable<T> source, Func<T, (TKey, TValue)> function, Func<TKey, TKey, bool> equalFunction) where TKey : notnull => new(RedStarLinq.ToList(source, function), equalFunction);
	public static Dictionary<TKey, TValue> ToDictionary<T, TKey, TValue>(this G.IEnumerable<T> source, Func<T, int, (TKey, TValue)> function, Func<TKey, TKey, bool> equalFunction) where TKey : notnull => new(RedStarLinq.ToList(source, function), equalFunction);
	public static Dictionary<TKey, TValue> ToDictionary<T, TKey, TValue>(this G.IEnumerable<T> source, Func<T, (TKey, TValue)> function, Func<TKey, TKey, bool> equalFunction, Func<TKey, int> hashCodeFunction) where TKey : notnull => new(RedStarLinq.ToList(source, function), equalFunction, hashCodeFunction);
	public static Dictionary<TKey, TValue> ToDictionary<T, TKey, TValue>(this G.IEnumerable<T> source, Func<T, int, (TKey, TValue)> function, Func<TKey, TKey, bool> equalFunction, Func<TKey, int> hashCodeFunction) where TKey : notnull => new(RedStarLinq.ToList(source, function), equalFunction, hashCodeFunction);
	public static Dictionary<TKey, TValue> ToDictionary<T, TKey, TValue>(this G.IEnumerable<T> source, Func<T, G.KeyValuePair<TKey, TValue>> function) where TKey : notnull => new(RedStarLinq.ToList(source, function));
	public static Dictionary<TKey, TValue> ToDictionary<T, TKey, TValue>(this G.IEnumerable<T> source, Func<T, int, G.KeyValuePair<TKey, TValue>> function) where TKey : notnull => new(RedStarLinq.ToList(source, function));
	public static Dictionary<TKey, TValue> ToDictionary<T, TKey, TValue>(this G.IEnumerable<T> source, Func<T, G.KeyValuePair<TKey, TValue>> function, G.IEqualityComparer<TKey> comparer) where TKey : notnull => new(RedStarLinq.ToList(source, function), comparer);
	public static Dictionary<TKey, TValue> ToDictionary<T, TKey, TValue>(this G.IEnumerable<T> source, Func<T, int, G.KeyValuePair<TKey, TValue>> function, G.IEqualityComparer<TKey> comparer) where TKey : notnull => new(RedStarLinq.ToList(source, function), comparer);
	public static Dictionary<TKey, TValue> ToDictionary<T, TKey, TValue>(this G.IEnumerable<T> source, Func<T, G.KeyValuePair<TKey, TValue>> function, Func<TKey, TKey, bool> equalFunction) where TKey : notnull => new(RedStarLinq.ToList(source, function), equalFunction);
	public static Dictionary<TKey, TValue> ToDictionary<T, TKey, TValue>(this G.IEnumerable<T> source, Func<T, int, G.KeyValuePair<TKey, TValue>> function, Func<TKey, TKey, bool> equalFunction) where TKey : notnull => new(RedStarLinq.ToList(source, function), equalFunction);
	public static Dictionary<TKey, TValue> ToDictionary<T, TKey, TValue>(this G.IEnumerable<T> source, Func<T, G.KeyValuePair<TKey, TValue>> function, Func<TKey, TKey, bool> equalFunction, Func<TKey, int> hashCodeFunction) where TKey : notnull => new(RedStarLinq.ToList(source, function), equalFunction, hashCodeFunction);
	public static Dictionary<TKey, TValue> ToDictionary<T, TKey, TValue>(this G.IEnumerable<T> source, Func<T, int, G.KeyValuePair<TKey, TValue>> function, Func<TKey, TKey, bool> equalFunction, Func<TKey, int> hashCodeFunction) where TKey : notnull => new(RedStarLinq.ToList(source, function), equalFunction, hashCodeFunction);
	public static Dictionary<T, T2> ToDictionary<T, T2>(this G.IEnumerable<T> source, G.IEnumerable<T2> source2) where T : notnull => new(source, source2);
	public static Dictionary<T, T2> ToDictionary<T, T2>(this G.IEnumerable<T> source, G.IEnumerable<T2> source2, G.IEqualityComparer<T> comparer) where T : notnull => new(source, source2, comparer);
	public static Dictionary<T, T2> ToDictionary<T, T2>(this G.IEnumerable<T> source, G.IEnumerable<T2> source2, Func<T, T, bool> equalFunction) where T : notnull => new(source, source2, equalFunction);
	public static Dictionary<T, T2> ToDictionary<T, T2>(this G.IEnumerable<T> source, G.IEnumerable<T2> source2, Func<T, T, bool> equalFunction, Func<T, int> hashCodeFunction) where T : notnull => new(source, source2, equalFunction, hashCodeFunction);
	public static Dictionary<T, T2> ToDictionary<T, T2>(this (G.IEnumerable<T>, G.IEnumerable<T2>) source) where T : notnull => new(source.Item1, source.Item2);
	public static Dictionary<T, T2> ToDictionary<T, T2>(this (G.IEnumerable<T>, G.IEnumerable<T2>) source, G.IEqualityComparer<T> comparer) where T : notnull => new(source.Item1, source.Item2, comparer);
	public static Dictionary<T, T2> ToDictionary<T, T2>(this (G.IEnumerable<T>, G.IEnumerable<T2>) source, Func<T, T, bool> equalFunction) where T : notnull => new(source.Item1, source.Item2, equalFunction);
	public static Dictionary<T, T2> ToDictionary<T, T2>(this (G.IEnumerable<T>, G.IEnumerable<T2>) source, Func<T, T, bool> equalFunction, Func<T, int> hashCodeFunction) where T : notnull => new(source.Item1, source.Item2, equalFunction, hashCodeFunction);
	public static Dictionary<T, T2> ToDictionary<T, T2>(this G.IEnumerable<(T, T2)> source) where T : notnull => new(source);
	public static Dictionary<T, T2> ToDictionary<T, T2>(this G.IEnumerable<(T, T2)> source, G.IEqualityComparer<T> comparer) where T : notnull => new(source, comparer);
	public static Dictionary<T, T2> ToDictionary<T, T2>(this G.IEnumerable<(T, T2)> source, Func<T, T, bool> equalFunction) where T : notnull => new(source, equalFunction);
	public static Dictionary<T, T2> ToDictionary<T, T2>(this G.IEnumerable<(T, T2)> source, Func<T, T, bool> equalFunction, Func<T, int> hashCodeFunction) where T : notnull => new(source, equalFunction, hashCodeFunction);
	public static Dictionary<T, T2> ToDictionary<T, T2>(this G.IEnumerable<G.KeyValuePair<T, T2>> source) where T : notnull => new(source);
	public static Dictionary<T, T2> ToDictionary<T, T2>(this G.IEnumerable<G.KeyValuePair<T, T2>> source, G.IEqualityComparer<T> comparer) where T : notnull => new(source, comparer);
	public static Dictionary<T, T2> ToDictionary<T, T2>(this G.IEnumerable<G.KeyValuePair<T, T2>> source, Func<T, T, bool> equalFunction) where T : notnull => new(source, equalFunction);
	public static Dictionary<T, T2> ToDictionary<T, T2>(this G.IEnumerable<G.KeyValuePair<T, T2>> source, Func<T, T, bool> equalFunction, Func<T, int> hashCodeFunction) where T : notnull => new(source, equalFunction, hashCodeFunction);
}
